name: Generate requirements.txt

on:
  pull_request:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "uv.lock"

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Generate requirements.txt
        run: uv export --format=requirements.txt --no-hashes --no-dev --no-annotate > requirements.txt

      - name: Check if requirements.txt changed
        id: check-changes
        run: |
          if git diff --quiet requirements.txt; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.check-changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add requirements.txt
          git commit -m "Auto-update requirements.txt from pyproject.toml"
          git push
